---
title: "Documentation"
output: github_document
---

## Example


```{r example}
library(onetime)

# Setup
otd <- tempdir(check = TRUE)
oo <- options(onetime.dir = otd)
ids  <- paste0("onetime-readme-", sample(1e9, 5L))


for (i in 1:5) {
  cat("Loop ", i, " of 5\n")
  onetime_do(cat("This command will only be run once.\n"), id = ids[1])
  onetime_warning("This warning will only be shown once.", id = ids[2])
  onetime_message("This message will only be shown once.", id = ids[3])
}

# Meanwhile, in a separate process:
library(callr)
result <- callr::r(function (ids, otd) {
  options(onetime.dir = otd)
  onetime::onetime_message("This message with an existing ID will not be shown.", id = ids[1])
  onetime::onetime_message("This message with a new ID will be shown.", id = ids[4])
}, show = TRUE, args = list(ids = ids, otd = otd))


# Letting the user hide a message:
onetime_message_confirm("A message that the user might want to hide.\n",
                        "In non-interactive sessions, instructions will ",
                        "be shown for hiding it manually.", id = ids[5])

```


```{r, echo = FALSE}
options(oo)
```

