# Generated by doctest: do not edit by hand
# Please edit file in R/utils.R

test_that("Doctest: onetime_mark_as_done", {
  # Created from @doctest for `onetime_mark_as_done`
  # Source file: R/utils.R
  # Source line: 60
  oo <- options(onetime.dir = tempdir(check = TRUE))
  id <- sample(10000L, 1)
  expect_true(onetime_mark_as_done(id = id))
  expect_silent(onetime_message("Won't be shown", id = id))
  onetime_reset(id = id)
  options(oo)
})

