# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Mods by DHJ to only build README
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    paths: ['README.Rmd']

name: render-rmarkdown

jobs:
  render-rmarkdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rmarkdown, local::. 
      - name: Render README.Rmd and Commit Results
        run: |
          Rscript -e 'rmarkdown::render("README.Rmd")' 
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit README.md -m 'Rebuild Rmarkdown files' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
